name: arinar
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025a=h04d1e81_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - beautifulsoup4==4.13.3
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - filelock==3.17.0
      - fsspec==2025.3.0
      - gdown==5.2.0
      - google-auth==2.38.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.70.0
      - h5py==3.13
      - huggingface-hub==0.29.2
      - idna==3.10
      - jinja2==3.1.6
      - markdown==3.7
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pillow==11.1.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pysocks==1.7.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.5.3
      - scipy==1.15.2
      - soupsieve==2.6
      - sympy==1.13.3
      - tensorboard==2.10.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - timm==0.9.12
      - torch==2.4.1
      - -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity
      - torchvision==0.19.1
      - tqdm==4.67.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
